#!/bin/bash

echo "🚀 Push to GitHub with Personal Access Token"
echo "============================================"

echo ""
echo "📋 Steps to create Personal Access Token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Set Note: 'Render Deployment'"
echo "4. Set Expiration: 90 days"
echo "5. Select scopes:"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ workflow (Update GitHub Action workflows)"
echo "6. Click 'Generate token'"
echo "7. Copy the token (you won't see it again!)"
echo ""

echo "🔑 After creating the token, run:"
echo "   git push origin main"
echo ""
echo "💡 When prompted:"
echo "   Username: gettechthings-del"
echo "   Password: [paste your Personal Access Token]"
echo ""

echo "✅ Git is configured with:"
echo "   Name: $(git config --global user.name)"
echo "   Email: $(git config --global user.email)"
echo "   Remote: $(git remote get-url origin)"
echo "" 